### ISSUE TITLE
duplicated ShareExtension resources in project.pbxproj when running "expo prebuild" multiple times 

### ISSUE THREAD

**Issue by lalalic** [langtube/expo-config-plugin-ios-share-extension#13]
multiple times execution of expo prebuild lead to duplicated ShareExtension records in project.pbxproj in various sections. 
This duplication would fail ios build with following error and warning message:

_Multiple targets match implicit dependency for product reference 'ShareExtension.appex'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'xxxxx' from project 'xxxx')
❌  error: Unexpected duplicate tasks:
⚠️  Skipping duplicate file: ../../Library/Developer/Xcode/DerivedData/xxxxx-hiyqnkzpncbwehflcjvlfnpfxdxt/Build/Products/Debug-iphonesimulator/ShareExtension.appex_

Looking into project.pbxproj, a few duplicated files of ShareExtension are added in sections, such as 

/* Begin PBXCopyFilesBuildPhase section */
		CB6F9DCFDE2641E4A2AB9A39 /* Copy Files */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 2147483647;
			dstPath = "";
			dstSubfolderSpec = 13;
			files = (
				6BE821E4473E4D09AAA9A2AE /* ShareExtension.appex in Copy Files */,
				75B31DE86070421C8CEC7A5D /* ShareExtension.appex in Copy Files */,
			);
			name = "Copy Files";
			runOnlyForDeploymentPostprocessing = 0;
		};
		D75640C801CB4298BAF84E22 /* Copy Files */ = {
			isa = PBXCopyFilesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			name = "Copy Files";
			dstPath = "";
			dstSubfolderSpec = 13;
		};
/* End PBXCopyFilesBuildPhase section */

**Comment by timedtext** [comment]
Hi, please provide a reproducible demo.

**Comment by lalalic** [comment]
@timedtext Thanks for your quick response. 

After debugging expo source code, I found that it's caused by multiple versions of @expo/config-plugins in my project. Your plugin uses 5.0.4, while the main project is using 5.0.1. I'll have to resolve it as an environmental issue.

**Comment by timedtext** [comment]
This is a known issue and will be fixed later.

**Comment by lalalic** [comment]
@timedtext 
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/expo-config-plugin-ios-share-extension/src/withShareExtensionXcodeTarget.ts b/node_modules/expo-config-plugin-ios-share-extension/src/withShareExtensionXcodeTarget.ts
index 4cbdfd2..9b770b4 100644
--- a/node_modules/expo-config-plugin-ios-share-extension/src/withShareExtensionXcodeTarget.ts
+++ b/node_modules/expo-config-plugin-ios-share-extension/src/withShareExtensionXcodeTarget.ts
@@ -28,6 +28,10 @@ export const withShareExtensionXcodeTarget: ConfigPlugin = (config) => {
 
     const pbxProject = config.modResults;
 
+    if(!!pbxProject.pbxTargetByName(extensionName)){
+      return config
+    }
+
     const target = pbxProject.addTarget(extensionName, 'app_extension', extensionName);
 
     // Add a new PBXSourcesBuildPhase for our ShareViewController
```
