### ISSUE TITLE
Taking a screenshot with iPhone and immediately sharing it using the share extension does not work

### ISSUE THREAD

**Issue by ChristopherGabba** [langtube/expo-config-plugin-ios-share-extension#18]
Taking a screenshot of anything using any up to date iPhone (i've replicated it on iPhone 12 and iPhone 15) and immediately using the share extension does open the app, it just flickers.  I cannot receive any data into the app to see if I can get the image file URL. Here is a video replicating the behavior:

https://github.com/timedtext/expo-config-plugin-ios-share-extension/assets/122328438/75d71e85-d338-473f-9228-ddbfa1487ec1

Please let me know if you have any questions. Here are my activation rules in app.json:

```javascript
      [
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
            "NSExtensionActivationSupportsText": true,
            "NSExtensionActivationSupportsWebURLWithMaxCount": 1,
            "NSExtensionActivationSupportsWebPageWithMaxCount": 1,
            "NSExtensionActivationSupportsImageWithMaxCount": 1,
            "NSExtensionActivationSupportsMovieWithMaxCount": 1
          }
        }
      ],
```

Everything else seems to work great (photo library, web pages, etc.).

Thanks,
Chris

**Comment by timedtext** [comment]
This plugin currently only supports accepting URL links. For receiving images, please refer to [this repository](https://github.com/achorein/expo-share-intent-demo).

**Comment by ChristopherGabba** [comment]
I apologize @timedtext, opened a new issue there: https://github.com/achorein/expo-share-intent-demo/issues/28#issue-2083781332
